apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80          # Exposes the service on port 80 (HTTP)
      targetPort: 5000  # Forwards traffic to container's port 5000
  type: LoadBalancer     # Creates an AWS ELB to expose the app publicly
